spring:
  application:
    name: kanban-tool
  datasource:
    url: jdbc:h2:file:/media/himanshu/Backup/gitfolder/KanBanApplication/src/main/resources/h2filedb/kanban-data;AUTO_SERVER=true
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  security:
    user:
      name: user
      password: password

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted