spring:
  application:
  name: kanban-tool

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tag:
      application: kanban-tool
  endpoint:
    prometheus:
      enable: true
